node {
    
    def mvnHome = tool 'Maven3'
     stage ('checkout') {
        checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: '3f1e3225-53a8-4846-8783-32c34d92f085', url: 'https://github.com/okadjenn/MyNewApplicationRepo2/']]])
    }

    stage ('build') {
        sh "${mvnHome}/bin/mvn clean install -f MyWebApp/pom.xml"
    }
    
     stage ('Code Quality scan')  {
       withSonarQubeEnv('Sonarqube') {
       sh "${mvnHome}/bin/mvn -f MyWebApp/pom.xml sonar:sonar"
        }
   }
   
    stage ('Code coverage')  {
       jacoco()
   }
   
    stage ('Nexus upload')  {
        nexusArtifactUploader(
        nexusVersion: 'nexus3',
        protocol: 'http',
        nexusUrl: 'http://ec2-100-26-210-132.compute-1.amazonaws.com:8081',
        groupId: 'myGroupId',
        version: '1.0-SNAPSHOT',
        repository: 'maven-snapshots',
        credentialsId: 'ed3db8a1-862d-427b-a62f-f8ffa2938ba1',
        artifacts: [
            [artifactId: 'MyWebApp',
             classifier: '',
             file: 'MyWebApp/target/MyWebApp.war',
             type: 'war']
           ]
        )
    }
    
    stage ('DEV Deploy')  {
      echo "deploying to DEV Env "
      deploy adapters: [tomcat9(credentialsId: 'ffdc2e37-0d0c-412e-b149-7879ed8296ce', path: '', url: 'http://ec2-3-84-238-50.compute-1.amazonaws.com:8080')], contextPath: null, war: '**/*.war'

    }
    
    stage ('DEV Approve')  {
            echo "Taking approval from Manager for QA Deploy"     
            timeout(time: 7, unit: 'DAYS') {
            input message: 'Do you approve to deploy into QA environment?', submitter: 'admin'
        }
    }
    
    stage ('QA Deploy')  {
       echo "deploying into QA Env "  
      deploy adapters: [tomcat9(credentialsId: 'ffdc2e37-0d0c-412e-b149-7879ed8296ce', path: '', url: 'http://ec2-3-84-238-50.compute-1.amazonaws.com:8080')], contextPath: null, war: '**/*.war'
    }
    
    stage ('QA Approve')  {
    echo "Taking approval from QA manager"
    timeout(time: 7, unit: 'DAYS') {
        input message: 'Do you want to proceed to PROD Deploy?', submitter: 'admin,manager_userid'
       }
    }

    stage ('PROD Deploy')  {
     echo "deploying into PROD Env " 
       deploy adapters: [tomcat9(credentialsId: 'ffdc2e37-0d0c-412e-b149-7879ed8296ce', path: '', url: 'http://ec2-3-84-238-50.compute-1.amazonaws.com:8080')], contextPath: null, war: '**/*.war'
    }
    
    
}
